title: Timothy Chiu  # your name (or website title) here
logo: "/images/headshot_Timothy Chiu.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Purpose-Driven Data Practitioner at Abbott Diagnostics
  <br><br>
  M.S. in Data Science (Magna cum laude) at Northwestern University since 6/2023
  <br>
  <small>AI/ML Modeling and Analytics Management focus</small>
  <br><br>
  Main driving forces of my work are data-backed innovation and informed decision making. I am eager to leverage and manage advanced data analytics to continuously improve healthcare technology, quality and access.
  <br><br>
  <a href="https://www.linkedin.com/in/timothy-chiu-89517334/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
